name: Build GitBuilding Docs

on: [push]
jobs:

  test:
    runs-on: [codeberg-tiny, codeberg-tiny-lazy]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: list directory contents
        run: ls -la
      - name: install GitBuilding
        run: |
          pipx install gitbuilding
          pipx ensurepath
          source ~/.bashrc
          cd docs
          gitbuilding build-html