name: Build GitBuilding Docs

on: [push, workflow_dispatch]
jobs:

  test:
    runs-on: [codeberg-tiny, codeberg-tiny-lazy]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: list directory contents
        run: ls -la
      - name: install GitBuilding
        run: |
          pip install --user gitbuilding
          export PATH="$HOME/.local/bin:$PATH"
          cd docs
          gitbuilding build-html