name: Build GitBuilding Docs

on: 
  workflow_dispatch:
jobs:

  test:
    runs-on: [codeberg-tiny, codeberg-tiny-lazy]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build docs
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install gitbuilding
          cd docs
          gitbuilding build-html